config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  devise_scope :user do
    get 'login', to:
    'devise/sessions#new'
  end
  devise_scope :user do
    get 'signup', to:
    'devise/registrations#new'
  end
  
  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end
  
  namespace :private do 
    resources :conversations, only: [:create] do
      member do
        post :close
        post :open
      end
    end
    resources :messages, only: [:index, :create]
  end
  
end
#1.added root to: 'pages#index'

#2 Here I’ve used a resources method to declare routes for
# index, show, new, edit, create, update and destroy actions. 

#Then I’ve declared some custom collection routes to access pages with multiple Post instances.
#These pages are going to be dedicated for separate branches

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/models/private.rb
module Private
  def self.table_name_prefix
    'private_'
  end
end

app/models/private/conversation.rb
class Private::Conversation < ApplicationRecord
    self.table_name = 'private_conversations'
    
        has_many :messages, 
                   class_name: "Private::Message", 
                   foreign_key: :conversation_id
        belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
        belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
        
        scope :between_users, -> (user1_id, user2_id) do
            where(sender_id: user1_id, recipient_id: user2_id).or(
              where(sender_id: user2_id, recipient_id: user1_id)
            )
        end
        
        scope :all_by_user, -> (user_id) do
            where(recipient_id: user_id).or(where(sender_id: user_id))
        end
        
        def opposed_user(user)
            user == recipient ? sender : recipient
        end

end

app/models/private/message.rb
class Private::Message < ApplicationRecord
    self.table_name = 'private_messages'
    after_create_commit do 
    Private::MessageBroadcastJob.perform_later(self, previous_message)
  end
  belongs_to :user
  belongs_to :conversation, 
             class_name: 'Private::Conversation',
             foreign_key: :conversation_id

  validates :body, presence: true
  validates :user_id, presence: true

  def previous_message
    previous_message_index = self.conversation.messages.index(self) - 1
    self.conversation.messages[previous_message_index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  # The dependent: :destroy argument says, when a user gets deleted,
  # all posts what the user has created will be deleted too.
  
  has_many :private_messages, class_name: 'Private::Message'
	has_many  :private_conversations, 
	          foreign_key: :sender_id, 
	          class_name: 'Private::Conversation'
	          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :opened_conversations_windows
   
    def opened_conversations_windows
        if user_signed_in?
          # opened conversations
          session[:private_conversations] ||= []
          @private_conversations_windows = Private::Conversation.includes(:recipient, :messages).find(session[:private_conversations])
        else
          @private_conversations_windows = []
          
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    #Since in our app the PagesController is responsible for the homepage, 
    #we’ll need to query data inside the pages_controller.rb file’s index action. 
    #Inside the index action retrieve some records from the posts table.
    #Assign the retrieved records to an instance variable,
    #so the retrieved objects are going to be available inside the home page’s views
    
    
    def index
        @posts = Post.limit(5)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def show
        @post = Post.find(params[:id])
        if user_signed_in?
            @message_has_been_sent = conversation_exist? 
        end
    end
    
    private

      def conversation_exist?
        Private::Conversation.between_users(current_user.id, @post.user.id).present?
      end

end

app/controllers/private/conversations_controller.rb
class Private::ConversationsController < ApplicationController
    
    def create
        recipient_id = Post.find(params[:post_id]).user.id
        @conversation = Private::Conversation.new(sender_id: current_user.id, 
                                                 recipient_id: recipient_id)
        if @conversation.save
          Private::Message.create(user_id: current_user.id, 
                                  conversation_id: @conversation.id, 
                                  body: params[:message_body])
    
          add_to_conversations unless already_added?
    
          respond_to do |format|
            format.js {render partial: 'posts/show/contact_user/message_form/success'}
          end
        else
          respond_to do |format|
            format.js {render partial: 'posts/show/contact_user/message_form/fail'}
          end
        end
    end
    
    private
    
      def add_to_conversations
        session[:private_conversations] ||= []
        session[:private_conversations] << @conversation.id
      end
    
      def already_added?
        session[:private_conversations].include?(@conversation.id)
      end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    #This code overwrites the sign_up_params and account_update_paramsmethods to accept the :name attribute.
    #As you see, those methods are in the Devise RegistrationsController, so we specified it and altered its methods.
    #Now inside our routes we have to specify this controller, so these methods could be overwritten.
    
    private
    
    def sign_up_params
        params.require(:user).permit( :name,
                                      :email,
                                      :password,
                                      :password_confirmation
                                      )
    end
    
    def account_update_params
        params.require(:user).permit( :name,
                                      :email,
                                      :password,
                                      :password_confirmation,
                                      :current_password
                                      )
    end
                                  
    
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
    include NavigationHelper
    include Private::ConversationsHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
    
    def collapsible_links_partial_path
        if user_signed_in?
            'layouts/navigation/collapsible_elements/signed_in_links'
        else
            'layouts/navigation/collapsible_elements/non_signed_in_links'
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    
  def contact_user_partial_path
    if user_signed_in?
      @post.user.id != current_user.id ? 'posts/show/contact_user' : 'shared/empty_partial'
    else 
      'posts/show/login_required'
    end
  end

  def leave_message_partial_path
    if @message_has_been_sent
      'posts/show/contact_user/already_in_touch'
    else
      'posts/show/contact_user/message_form'
    end
  end
  
end

app/helpers/private/conversations_helper.rb
module Private::ConversationsHelper
    
    # get the opposite user of the conversation
    def private_conv_recipient(conversation)
        conversation.opposed_user(current_user)
    end
    
    # if the conversation has unshown messages, create a link to get them
    def load_private_messages(conversation)
        if conversation.messages.count > 0 
          'private/conversations/conversation/messages_list/link_to_previous_messages'
        else
          'shared/empty_partial'
        end 
    end



end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
        <div class="row">
    
          <!-- Elements visible all the time -->
          <div class="col-sm-7">
            
            <!-- The line below is added to import partial header html file -->
              <%= render 'layouts/navigation/header' %>
          </div><!-- col-sm-7 -->
    
          <!-- Elements collapses on smaller devices -->
          <div class="col-sm-5">
            <!-- The line below is added to import partial collapsible html file -->
            <%= render 'layouts/navigation/collapsible_elements' %>
          </div><!-- col-sm-5 -->
    
        </div><!-- row -->
    <!-- Brand and toggle get grouped for better mobile display -->
   

    <!-- Collect the nav links, forms, and other content for toggling -->
    
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollabApp</title>
    <%= csrf_meta_tags %>
    <%= include_gon(:init => true) %>
     <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= render 'layouts/application/private_conversations_windows' %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
      <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
 <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--a class="navbar-brand" href="#">Brand</a-->
      <%= link_to 'Manchester United', root_path, class: 'navbar-brand' %>
    </div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Login', login_path %></li>
      <li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown pc-menu">
        <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span id="user-name"><%= current_user.name %></span>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <li class="mobile-menu">
        <%= link_to 'Edit Profile', edit_user_registration_path %>
      </li>
      <li class="mobile-menu">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

app/views/posts/_modal.html.erb
<!-- Modal -->
<div  class="modal myModal" 
      tabindex="-1" 
      role="dialog" 
      aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="posted-by"></span>
        <button type="button" 
                class="close" 
                data-dismiss="modal" 
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <div class="loaded-data">
            <h3></h3>
            <p></p>
            <div class="interested"><a href="">I'm interested</a></div>
          </div><!-- loaded-data -->
        </div><!-- modal-body -->
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="col-sm-3 single-post-card" id=<%= post_path(post.id) %>>
  <div class="card">
    <div class="card-block">
      <h4 class="post-text">
        <%= truncate(post.title, :length => 60) %>
      </h4>
      <div class="post-content">
        <div class="posted-by">Posted by <%= post.user.name %></div>
        <h3><%= post.title %></h3> 
        <p><%= post.content %></p>
        <%= link_to "Learn More", post_path(post.id), class: 'interested' %>
      </div>
    </div>
  </div><!-- card -->
</div><!-- col-sm-3 -->
<!--
#I’ve used a bootstrap card component here to achieve the desired style.
#Then I just stored post’s content and its path inside the element. 
#Also I added a link which will lead to the full post.
-->

app/views/posts/show.html.erb
<div id="single-post-content" class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Posted by <%= @post.user.name %></div>
      <h3><%= @post.title %></h3>
      <p><%= @post.content %></p>
      <%= render partial: contact_user_partial_path %>
    </div>
  </div><!-- row -->
</div>

app/views/posts/show/_contact_user.html.erb
<div class="contact-user">
  <%= render leave_message_partial_path %>
</div><!-- contact-user -->

app/views/posts/show/_login_required.html.erb
<div class="text-center">
  To contact the user you have to <%= link_to 'Login', login_path %> 
</div>

app/views/posts/show/contact_user/_already_in_touch.html.erb
<div class="contacted-user">
You are already in touch with this user
</div>

app/views/posts/show/contact_user/_message_form.html.erb
<%= form_tag({controller: "private/conversations", action: "create"},
              method: "post",
              remote: true) do %>
  <%= hidden_field_tag(:post_id, @post.id)  %>
  <%= text_area_tag(:message_body,
                    nil,
                    rows: 3,
                    class: 'form-control', 
                    placeholder: 'Send a messsage to the user') %>
  <%= submit_tag('Send a message', class: 'btn send-message-to-user') %>
<% end %>

app/views/posts/show/contact_user/message_form/_fail.js.erb
$('.contact-user').replaceWith('<div>Message has not been sent</div>');

app/views/posts/show/contact_user/message_form/_success.js.erb
$('.contact-user').replaceWith('\
    <div class="contact-user">\
        <div class="contacted-user">Message has been sent</div>\
    </div>');
<%= render 'private/conversations/open' %>

app/views/private/conversations/_conversation.html.erb
<% @recipient = private_conv_recipient(conversation) %>
<% @is_messenger = false %>
<li class="conversation-window" 
    id="pc<%= conversation.id %>" 
    data-pconversation-user-name="<%= @recipient.name %>" 
    data-turbolinks-permanent>
  <div class="panel panel-default" data-pconversation-id="<%= conversation.id %>">
    <%= render 'private/conversations/conversation/heading', 
                conversation: conversation %>

    <!-- Conversation window's content -->
    <div class="panel-body">
      <%= render 'private/conversations/conversation/messages_list', 
                  conversation: conversation %>
      <%= render 'private/conversations/conversation/new_message_form', 
                  conversation: conversation,
                  user: user %>
    </div><!-- panel-body -->
  </div>
</li><!-- conversation-window -->

app/views/private/conversations/_open.js.erb
var conversation = $('body').find("[data-pconversation-id='" + 
                                "<%= @conversation.id %>" + 
                                "']");
var chat_windows_count = $('.conversation-window').length + 1;

if (conversation.length !== 1) {
  $('body').append("<%= j(render 'private/conversations/conversation',\
                                  conversation: @conversation,\
                                  user: current_user) %>");
  conversation = $('body').find("[data-conversation-id='" + 
                                "<%= @conversation.id %>" + 
                                "']");
}

// Toggle conversation window after its creation
$('.conversation-window:nth-of-type(' + chat_windows_count + ')\
   .conversation-heading').click();
// mark as seen by clicking it
setTimeout(function(){ 
  $('.conversation-window:nth-of-type(' + chat_windows_count + ')').click();
 }, 1000);
// focus textarea
$('.conversation-window:nth-of-type(' + chat_windows_count + ')\
   form\
   textarea').focus();

// repositions all conversation windows
positionChatWindows();

app/views/private/conversations/conversation/_heading.html.erb
<div class="panel-heading <%= conv_heading_class(@contact) %>">
  <span class="contact-name-notif"><%= @recipient.name %></span>  
</div> <!-- conversation-heading -->

<!-- Close conversation button -->
<%= link_to "X", 
            close_private_conversation_path(conversation), 
            class: 'close-conversation', 
            title: 'Close', 
            remote: true, 
            method: :post %>

<%= render add_to_contacts_partial_path(@contact) %>
<%= render create_group_conv_partial_path(@contact), 
					 conversation: conversation %>

app/views/private/conversations/conversation/_messages_list.html.erb
<div class="messages-list">
  <%= render load_private_messages(conversation), conversation: conversation %>
  <div class="loading-more-messages">
    <i class="fa fa-spinner" aria-hidden="true"></i>
  </div>
  <!-- messages -->
  <ul>
  </ul>
</div>

app/views/private/conversations/conversation/_new_message_form.html.erb
<form class="send-private-message">
  <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
  <input name="user_id" type="hidden" value="<%= user.id %>">
  <textarea name="body" rows="3" class="form-control" placeholder="Type a message..."></textarea>
  <input type="submit" class="btn btn-success send-message">
</form>

app/views/private/conversations/conversation/messages_list/_link_to_previous_messages.html.erb
<%= link_to "Load messages", 
            private_messages_path(:conversation_id => conversation.id, 
                                  :messages_to_display_offset => @messages_to_display_offset,
                                  :is_messenger => @is_messenger),
            class: 'load-more-messages', 
            remote: true %>